---
resources:
- name: code
  type: git
  source:
    uri: git@github.com:mramuta/concourse-testing.git
    branch: master
    private_key: {{git-token}}


jobs:
- name: job-hello-world
  public: true
  plan:
  - get: code
  - task: hello-world
    file: code/tasks/ruby.yaml