---
resources:
- name: code
  type: git
  source:
    uri: git@github.com:mramuta/concourse-testing.git
    branch: master
    private_key: {{git-token}}


jobs:
- name: bash-script
  plan:
  - get: code
  - task: bash
    file: code/tasks/bash.yaml

- name: ruby-script
  plan:
  - get: code
  - task: ruby
    file: code/tasks/ruby.yaml